apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
spec:
 selector:
    matchLabels:
      app: account-service
 replicas: 1
 template:
   metadata:
     labels:
        app: account-service
   spec:
     containers:
     - name: account-service
       image: yassineelabdi05/account-service:latest
       ports:
       - containerPort: 8082